---
- name: Install required packages
  yum: name={{ item }} state=installed
  with_items:
   - ntpdate
   - ntp
   - vim
   - tcpdump
   - traceroute
#   - python-libselinux

#- name: Disable selinus
#  selinux: state=disabled

- name: Sync time with master-node
  command: ntpdate -u {{ntp_server}}
  ignore_errors: True
#- name: Sync time with ntp.ru
#  command: ntpdate -u ntp.ru
#  when: net16|skipped