---
- name: Install required packages
  yum: name={{ item }} state=installed
  with_items:
   - ntpdate
   - ntp
   - vim
   - tcpdump
   - traceroute

- name: Disable selinus
  selinux: state=disabled

- name: Sync time with master-node
  command: ntpdate -u fuel
