---
- name: Install required packages
  yum: name={{item}} state=installed
  with_items:
   - ntpdate
   - ntp
   - vim
   - tcpdump
   - traceroute
   - libselinux-python

- name: Disable selinus
  selinux: state=disabled

- name: Sync time with master-node
  command: ntpdate -u {{ntp_server}}
  ignore_errors: True

- service: name=ntpd  state=started  enabled=yes

- include: centos_network.yaml
  when: centos_network is defined and centos_network