---
# Setup pacemaker
# - name: "Prepare Cluster's parameters"
#   command: crm_attribute --type=crm_config {{item.val}}
#   with_items:
#     - val: "--name=no-quorum-policy --update=ignore"
#     - val: "--name=stonith-enabled --update=false"
#     - val: "--name=start-failure-is-fatal --update=false"
- name: "Prepare Cluster's parameters"
  command: pcs property set {{item.name}}={{item.value}}
  with_items:
    - name:  'no-quorum-policy'
      value: 'ignore'
    - name:  'stonith-enabled'
      value: 'false'
    - name:  'start-failure-is-fatal'
      value: 'false'
- name: "remove old test resource if it exists"
  shell: "pcs resource delete {{pacemaker_test_resource}}"
  ignore_errors: True
- name: "Create test resource"
  shell: "{{ item | replace('\n', '') }}"
  with_items:
    - >
      pcs resource create {{pacemaker_test_resource}} ocf:mirantis:test_masterslave
        meta master-max=1
        meta master-node-max=1
        meta notify=true
        meta interleave='true'
        meta is-managed='true'
        meta target-role='Stopped'
          op monitor interval='3' role='Master' timeout='10'
          op monitor interval='30' timeout='10'
          op start timeout='30'
          op stop timeout='30'
          op notify timeout='30'
          op demote timeout='30'
          op promote timeout='30'
    - pcs resource master master-{{pacemaker_test_resource}} {{pacemaker_test_resource}}
    - pcs resource enable {{pacemaker_test_resource}}
#