---
- name: "Install corosync, pacemaker, pcs, avahi"
  yum: >
    name={{item}}
    state=latest
    disable_gpg_check=yes
  with_items:
    - "corosync-1.4.6"
    - "pacemaker-1.1.10"
    - "pcs-0.9.103"
    - "avahi-tools"
    - "oddjob"
    - "nginx"
- yum: name=nss-mdns state=installed enablerepo=epel disable_gpg_check=yes
- service: name=messagebus state=started enabled=yes

- name: "Configure avahi/mdns"
  template: >
    src=avahi-daemon.conf.j2
    dest=/etc/avahi/avahi-daemon.conf
    backup=yes owner=root group=root mode=0644
  with_items:
    - bind_interface: "{{net_interfaces.cluster}}"
      domain_name: "{{domain}}"
  notify:
    - "Restart avahi-daemon"
- name: "Configure mdns resolving"
  lineinfile: >
    dest=/etc/nsswitch.conf
    regexp=^hosts:
    line="hosts: files mdns4_minimal [NOTFOUND=return]  dns mdns4"
    state=present create=yes backup=yes
- template: dest=/etc/mdns.allow src=mdns.allow.j2 backup=yes owner=root group=root mode=0644
- service: name=avahi-daemon state=started enabled=yes

- copy: src=limits.conf dest=/etc/security/limits.conf owner=root group=root mode=0644 backup=yes
- service: name=iptables state=stopped enabled=no

- name: "Configure Corosync"
  template: src=corosync1.conf.j2 dest=/etc/corosync/corosync.conf backup=yes owner=root group=root mode=0644
  with_items:
    - bind_address: "{{cluster_ipaddr}}"
      broadcast: "{{cluster_broadcast}}"
  notify:
    - Stop pacemaker-daemon
    - Restart corosync-daemon
    - Start pacemaker-daemon
- name: "check required directories"
  file: path={{item.name}} mode={{item.mode}} owner={{item.owner}} group={{item.group}} state=directory
  with_items:
    - name: /etc/corosync/service.d
      owner: root
      group: root
      mode:  '0755'
    - name: /var/lib/pacemaker/cores/root
      owner: hacluster
      group: haclient
      mode:  '0750'
    - name: /usr/lib/ocf/resource.d/mirantis
      owner: root
      group: root
      mode:  '0755'

- name: "Pacemaker as Corosync service"
  template: src=corosync1.service.j2 dest=/etc/corosync/service.d/{{item.name}} backup=yes owner=root group=root mode=0644
  with_items:
    - name: pacemaker
      version: 1
- service: name=corosync enabled=yes state=started
- service: name=pacemaker enabled=yes state=started

- name: "Install OCF scripts"
  copy: src=ocf/{{item.name}} dest=/usr/lib/ocf/resource.d/mirantis/{{item.name}} owner=root group=root mode=0755 backup=yes
  with_items:
    - name: test_masterslave
#