---
- name: "Deploy Pacemaker cluster"
  include: cluster_deploy.yaml
  when: cluster_deploy is defined
- name: "Configure Pacemaker cluster"
  include: cluster_configure.yaml
  when: cluster_configure is defined
